export const resultsMock = {
	count: 3,
	data: [
		{
			agency_name: "Cicero Police Department - IN",
			agency_supplied: false,
			airtable_uid: "rec7edsmcuVQwMMXG",
			coverage_end: null,
			coverage_start: "2017-01-01",
			data_source_name: "Calls for Service for Cicero Police Department - IN",
			description: null,
			municipality: "Bridgeview",
			name: "Cicero Police Department - IN",
			record_format: "[]",
			record_type: "Calls for Service",
			source_url:
				"https://cityprotect.com/agency/cc0d9a3d-50b2-4424-ae25-5699ba6eaff9",
			state_iso: "IN",
		},
		{
			agency_name: "Chicago Police Department - IL",
			agency_supplied: true,
			airtable_uid: "recv9fMNEQTbVarj2",
			coverage_end: null,
			coverage_start: "2019-01-01",
			data_source_name: "Calls for Service for Chicago Police Department - IL",
			description: null,
			municipality: "Chicago",
			name: "Chicago Police Department - IL",
			record_format: "[]",
			record_type: "Calls for Service",
			source_url:
				"https://informationportal.igchicago.org/911-calls-for-cpd-service/",
			state_iso: "IL",
		},
		{
			agency_name: "Chicago Police Department - IL",
			agency_supplied: false,
			airtable_uid: "recv9fMNEQTbVarj2",
			coverage_end: null,
			coverage_start: "2018-12-18",
			data_source_name: "311 Calls for City of Chicago",
			description:
				"311 Service Requests received by the City of Chicago. This dataset includes requests created after the launch of the new 311 system on 12/18/2018 and some records from the previous system, indicated in the LEGACY\\_RECORD column.\n\nIncluded as a Data Source because in some cities 311 calls lead to police response; that does not appear to be the case in Chicago.\n",
			municipality: "Chicago",
			name: "Chicago Police Department - IL",
			record_format: "['CSV', 'XML', 'RDF', 'RSS']",
			record_type: "Calls for Service",
			source_url:
				"https://data.cityofchicago.org/Service-Requests/311-Service-Requests/v6vf-nfxy",
			state_iso: "IL",
		},
	],
};

export const dataSourceMock = {
	name: "Calls for Service for Chicago Police Department - IL",
	submitted_name: "Chicago Police Department",
	description: null,
	record_type: "Calls for Service",
	source_url:
		"https://informationportal.igchicago.org/911-calls-for-cpd-service/",
	last_cached: "01/03/2024",
	agency_supplied: true,
	supplying_entity: null,
	agency_originated: null,
	originating_entity: null,
	agency_aggregation: null,
	coverage_start: "2019-01-01",
	coverage_end: null,
	source_last_updated: null,
	retention_schedule: null,
	detail_level: "Summarized totals",
	number_of_records_available: null,
	size: null,
	access_type: ["Web page"],
	data_portal_type: null,
	record_format: null,
	update_frequency: "Bi-weekly",
	update_method: null,
	tags: null,
	readme_url: null,
	scraper_url: null,
	data_source_created: "2022-09-28",
	airtable_source_last_modified: "2023-11-08",
	url_status: "ok",
	rejection_note: null,
	last_approval_editor:
		'{"id": "usrtLIB4Vr3jTH8Ro", "email": "josh.chamberlain@pdap.io", "name": "Josh Chamberlain"}',
	agency_described_submitted: "Chicago city, Illinois",
	agency_described_not_in_database: null,
	approval_status: "approved",
	record_type_other: null,
	data_portal_type_other: null,
	records_not_online: null,
	data_source_request: null,
	url_button: null,
	tags_other: null,
	access_notes: null,
	homepage_url: "https://home.chicagopolice.org/",
	count_data_sources: 21,
	agency_type: "law enforcement/police",
	multi_agency: null,
	jurisdiction_type: "local",
	state_iso: "IL",
	municipality: "Chicago",
	zip_code: "60616",
	county_fips: "17031",
	county_name: ["Cook"],
	lat: 41.85861,
	lng: -87.62802,
	data_sources: [
		"recs7gYAGAMWEhLYC",
		"recyR4IVgqyIekzYB",
		"recBMxu4UcHCqjsWQ",
		"recqXzWtmhfV9z8Av",
		"recc5QWeCMGL17Ab6",
		"recD9bNxneanhBBDH",
		"recPUGM4OEopoRAXB",
		"rec10Mts7CmMPzcnx",
		"recTj2zTdu7Jp8oX9",
		"rec00T2YLS2jU7Tbn",
		"recpOsfsTV4bKmVfa",
		"recipwTdMN0jRADrt",
		"recjFk7X0KofjTPGK",
		"rec0Lqwrj6blSbkuz",
		"recYyAY8XVQJJVde6",
		"recgwPuRTwjAMUZeO",
		"recOLt1yQGlgrO5jQ",
		"recdAte1fo5FBruE7",
		"recUGIoPQbJ6laBmr",
		"recTw75rItd827L0r",
		"rechI06qD4od759xT",
		"recodGxvuxiTXPnOL",
	],
	no_web_presence: null,
	airtable_agency_last_modified: "2023-05-16",
	data_sources_last_updated: "2023-04-06",
	approved: true,
	rejection_reason: null,
	agency_created: "2022-08-18",
	county_airtable_uid: "recuhY2ud60V41j0w",
	defunct_year: null,
	data_source_id: "rec00T2YLS2jU7Tbn",
	agency_id: "recv9fMNEQTbVarj2",
	agency_name: "Chicago Police Department - IL",
};
