GET_DATA_SOURCES_FOR_MAP_QUERY = """
SELECT
    DATA_SOURCES.id AS DATA_SOURCE_ID,
    L.ID as LOCATION_ID,
    DATA_SOURCES.NAME,
    AGENCIES.ID AS AGENCY_ID,
    AGENCIES.NAME AS AGENCY_NAME,
    S.STATE_ISO,
    LOC.name AS MUNICIPALITY,
    C.name,
    RT.NAME RECORD_TYPE,
    L.lng,
    L.lng
FROM
    LINK_AGENCIES__DATA_SOURCES AS AGENCY_SOURCE_LINK
        INNER JOIN DATA_SOURCES ON AGENCY_SOURCE_LINK.DATA_SOURCE_ID = DATA_SOURCES.ID
        INNER JOIN RECORD_TYPES RT ON RT.ID = DATA_SOURCES.RECORD_TYPE_ID
        INNER JOIN AGENCIES ON AGENCY_SOURCE_LINK.AGENCY_ID = AGENCIES.ID
        LEFT JOIN LINK_AGENCIES__LOCATIONS LAL ON AGENCIES.ID = LAL.AGENCY_ID
        LEFT JOIN LOCATIONS L ON LAL.location_id = L.ID
        LEFT JOIN us_states S ON L.state_id = S.id
        LEFT JOIN LOCALITIES LOC ON L.locality_id = LOC.id
        LEFT JOIN COUNTIES c on L.county_id = C.id

        """
