ROLE_COLUMN_PERMISSIONS = {
    "agencies_expanded": {
        "name": {"ADMIN": "READ", "STANDARD": "READ"},
        "submitted_name": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "homepage_url": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "jurisdiction_type": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "state_iso": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "county_fips": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "county_name": {"ADMIN": "READ", "STANDARD": "READ"},
        "lat": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "lng": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "defunct_year": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_type": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "no_web_presence": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "airtable_agency_last_modified": {"ADMIN": "READ", "STANDARD": "READ"},
        "approval_status": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "rejection_reason": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "last_approval_editor": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "submitter_contact": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_created": {"ADMIN": "READ", "STANDARD": "READ"},
        "locality_name": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "state_name": {"ADMIN": "READ", "STANDARD": "READ"},
        "id": {"ADMIN": "READ", "STANDARD": "READ"},
    },
    "agencies": {
        "name": {"STANDARD": "READ", "ADMIN": "WRITE"},
        "submitted_name": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "homepage_url": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "jurisdiction_type": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "lat": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "lng": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "defunct_year": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_type": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "multi_agency": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "no_web_presence": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "airtable_agency_last_modified": {"ADMIN": "READ", "STANDARD": "READ"},
        "approval_status": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "rejection_reason": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "last_approval_editor": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "submitter_contact": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_created": {"ADMIN": "READ", "STANDARD": "READ"},
        "county_airtable_uid": {"ADMIN": "READ", "STANDARD": "READ"},
        "location_id": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "id": {"ADMIN": "READ", "STANDARD": "READ"},
        "airtable_uid": {"ADMIN": "NONE", "STANDARD": "NONE"},
    },
    "data_requests": {
        "id": {"ADMIN": "READ", "STANDARD": "READ", "OWNER": "READ"},
        "submission_notes": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
        "request_status": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "READ"},
        "archive_reason": {"ADMIN": "WRITE", "STANDARD": "NONE", "OWNER": "READ"},
        "date_created": {"ADMIN": "READ", "STANDARD": "READ", "OWNER": "READ"},
        "date_status_last_changed": {
            "ADMIN": "READ",
            "STANDARD": "READ",
            "OWNER": "READ",
        },
        "creator_user_id": {"ADMIN": "READ", "STANDARD": "NONE", "OWNER": "READ"},
        "internal_notes": {"ADMIN": "WRITE", "STANDARD": "NONE", "OWNER": "NONE"},
        "record_types_required": {
            "ADMIN": "WRITE",
            "STANDARD": "READ",
            "OWNER": "READ",
        },
        "pdap_response": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "READ"},
        "coverage_range": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
        "data_requirements": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
        "request_urgency": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
        "title": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
        "github_issue_number": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "READ"},
        "github_issue_url": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "READ"},
    },
    "data_requests_expanded": {
        "id": {"ADMIN": "READ", "STANDARD": "READ", "OWNER": "READ"},
        "submission_notes": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
        "request_status": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "READ"},
        "archive_reason": {"ADMIN": "WRITE", "STANDARD": "NONE", "OWNER": "READ"},
        "date_created": {"ADMIN": "READ", "STANDARD": "READ", "OWNER": "READ"},
        "date_status_last_changed": {
            "ADMIN": "READ",
            "STANDARD": "READ",
            "OWNER": "READ",
        },
        "creator_user_id": {"ADMIN": "READ", "STANDARD": "NONE", "OWNER": "READ"},
        "internal_notes": {"ADMIN": "WRITE", "STANDARD": "NONE", "OWNER": "NONE"},
        "record_types_required": {
            "ADMIN": "WRITE",
            "STANDARD": "READ",
            "OWNER": "READ",
        },
        "pdap_response": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "READ"},
        "coverage_range": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
        "data_requirements": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
        "request_urgency": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
        "github_issue_number": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "READ"},
        "github_issue_url": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "READ"},
        "title": {"ADMIN": "WRITE", "STANDARD": "READ", "OWNER": "WRITE"},
    },
    "data_sources_expanded": {
        "name": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "description": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "source_url": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_supplied": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "supplying_entity": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_originated": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_aggregation": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "coverage_start": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "coverage_end": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "detail_level": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "data_portal_type": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "record_formats": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "update_method": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "tags": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "readme_url": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "originating_entity": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "retention_schedule": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "scraper_url": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "submission_notes": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_described_not_in_database": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "data_portal_type_other": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "data_source_request": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "broken_source_url_as_of": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "access_notes": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "url_status": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "record_type_id": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "record_type_name": {"ADMIN": "READ", "STANDARD": "READ"},
        "access_types": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "updated_at": {"ADMIN": "READ", "STANDARD": "READ"},
        "created_at": {"ADMIN": "READ", "STANDARD": "READ"},
        "id": {"ADMIN": "READ", "STANDARD": "READ"},
    },
    "data_sources": {
        "name": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "description": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "source_url": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_supplied": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "supplying_entity": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_originated": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_aggregation": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "coverage_start": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "coverage_end": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "detail_level": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "data_portal_type": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "record_formats": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "update_method": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "tags": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "readme_url": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "originating_entity": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "retention_schedule": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "scraper_url": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "agency_described_not_in_database": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "data_portal_type_other": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "data_source_request": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "broken_source_url_as_of": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "access_notes": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "url_status": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "record_type_id": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "access_types": {"ADMIN": "WRITE", "STANDARD": "READ"},
        "updated_at": {"ADMIN": "READ", "STANDARD": "READ"},
        "created_at": {"ADMIN": "READ", "STANDARD": "READ"},
        "id": {"ADMIN": "READ", "STANDARD": "READ"},
        "airtable_uid": {"ADMIN": "NONE", "STANDARD": "NONE"},
    },
}
