GET_DATA_SOURCES_FOR_MAP_QUERY = """
            SELECT
                DATA_SOURCES.id AS DATA_SOURCE_ID,
                LE.ID as LOCATION_ID,
                DATA_SOURCES.NAME,
                AGENCIES.ID AS AGENCY_ID,
                AGENCIES.NAME AS AGENCY_NAME,
                LE.STATE_ISO,
                LE.LOCALITY_NAME AS MUNICIPALITY,
                LE.COUNTY_NAME,
                RT.NAME RECORD_TYPE,
                AGENCIES.LAT,
                AGENCIES.LNG
            FROM
                LINK_AGENCIES_DATA_SOURCES AS AGENCY_SOURCE_LINK
                INNER JOIN DATA_SOURCES ON AGENCY_SOURCE_LINK.DATA_SOURCE_ID = DATA_SOURCES.ID
                INNER JOIN AGENCIES ON AGENCY_SOURCE_LINK.AGENCY_ID = AGENCIES.ID
                INNER JOIN LINK_AGENCIES_LOCATIONS LAL ON AGENCIES.ID = LAL.AGENCY_ID
                LEFT JOIN LOCATIONS_EXPANDED LE ON LAL.LOCATION_ID = LE.ID
                INNER JOIN RECORD_TYPES RT ON RT.ID = DATA_SOURCES.RECORD_TYPE_ID
            WHERE
                DATA_SOURCES.APPROVAL_STATUS = 'approved'
                AND LAT is not null
				AND LNG is not null
        """
