name: Extract Issue Numbers from PRs

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run script
        run: python .github/scripts/get_pr_issues.py
