name: Bandit Security Linting

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      run: |
        bandit -r middleware

    - name: Upload Bandit results
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report
        path: bandit_output.txt

