# This script will sync the production database environment
# to the dev database environment on a weekly basis
# It requires the following Github Secrets:
# PROD_DB_CONN_STRING: A connection string to the prod database
#   for user "prod_dump_agent"
# DEV_ADMIN_DB_CONN_STRING: A connection string to the development database
#   at database "defaultdb" for user "doadmin"
#   must be a separate string from DEV_DB_CONN_STRING
#   to enable closing and rebuilding the "pdab_dev_db" database.
# DEV_DB_CONN_STRING: A connection string to the development database
##   at database "pdap_dev_db" for user "doadmin"

name: Sync Production to Development

on:
  schedule:
    # Runs at 00:00 every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  sync-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shell script to dump and restore database
        run: |
          chmod +x ./github/scripts/dump_prod_to_dev.sh
          ./github/scripts/dump_prod_to_dev.sh
        env:
          PROD_DB_CONN_STRING: ${{ secrets.PROD_DB_CONN_STRING }}
          DEV_ADMIN_DB_CONN_STRING: ${{ secrets.DEV_ADMIN_DB_CONN_STRING }}
          DEV_DB_CONN_STRING: ${{ secrets.DEV_DB_CONN_STRING }}