name: Test using Pytest

on:
  pull_request:

jobs:
  run_tests:

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      FLASK_APP_COOKIE_ENCRYPTION_KEY: "cookieEncryptionKey"
      DO_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      GH_CLIENT_ID: "GithubProvidedClientId"
      GH_CLIENT_SECRET: "GithubProvidedClientSecret"
      JWT_SECRET_KEY: "TestSecretKey"
      RESET_PASSWORD_SECRET_KEY: "resetTokenSecretKey"
      VALIDATE_EMAIL_SECRET_KEY: "validateEmailSecretKey"

    name: Run Pytest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.8"
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt
        uv pip install --system pytest pytest-cov
    - name: Run migrations
      run: |
        alembic upgrade head
    - name: Run tests
      run: |
        pytest tests
        
      
