name: Test API using Pytest

on:
  pull_request:

jobs:
  test_api:
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEV_DB_CONN_STRING: ${{secrets.DEV_DB_CONN_STRING}}
    name: Test API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm
        pip install pytest pytest-cov
        pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
