DATA_SOURCES_BASE_ENDPOINT = "/api/data-sources/"

DATA_REQUESTS_BASE_ENDPOINT = "/api/data-requests/"
DATA_REQUESTS_BY_ID_ENDPOINT = DATA_REQUESTS_BASE_ENDPOINT + "by-id/"
DATA_REQUESTS_GET_RELATED_SOURCE_ENDPOINT = DATA_REQUESTS_BY_ID_ENDPOINT + "{data_request_id}/related-sources/"
DATA_REQUESTS_POST_DELETE_RELATED_SOURCE_ENDPOINT = DATA_REQUESTS_GET_RELATED_SOURCE_ENDPOINT + "{source_id}/"
